### PR TITLE
fixed png to jpg conversion while resize

### PR DESCRIPTION
**Pull request by akwatra**
when you used $handle->image_convert = 'jpg'; 
and  $handle->image_resize         = true; 
it was taking old file extension name as destination and image type data was resultant corrept image.

### CODE REVIEW

**Comment by akwatra** [comment]
To reproduce error at your end:
upload png image 
$handle->image_convert = 'jpg';

and do resize: 
$handle->image_background_color = '#FFFFFF';
	  	  $handle->image_ratio_fill = true;
		  $handle->image_resize         = true;
		  $handle->image_x              = 300;
		  $handle->image_y        		= 230;
 $handle->process($current_img_dir);

Image extension should be ".jpg" but it was creating png as this was taking 
$this->file_dst_pathname but this should take new file ext while creating jpg image in 
look into LINE 4795  
switch($this->image_convert) {
                        case 'jpeg':
                        case 'jpg':
                            if (!$return_mode) {
                                $result = @imagejpeg($image_dst, $this->file_dst_path . '/' . $this->file_dst_name_body .'.jpg', $this->jpeg_quality);
    
in log also taking the wrong extension, in this patch log also has to correct yet.

 ######## LOG #########
system information
- class version           : 0.35dev
- operating system        : Linux
- PHP version             : 7.2.1
- GD version              : 2.1.0
- supported image types   : png jpg gif bmp
- open_basedir            : no restriction
- upload_max_filesize     : 40M (41943040 bytes)
- language                : en_GB
source is a local file /www/html/php/tmp/php41vtHF
- local file OK
determining MIME type
- Checking MIME type with Fileinfo PECL extension
    MAGIC path will not be used
    MIME type detected as image/png; charset=binary by Fileinfo PECL extension
- MIME validated as image/png
source variables
- You can use all these before calling process()
    file_src_name         : php41vtHF
    file_src_name_body    : php41vtHF
    file_src_name_ext     : 
    file_src_pathname     : /www/html/php/tmp/php41vtHF
    file_src_mime         : image/png
    file_src_size         : 1254184 (max= 41943040)
    file_src_error        : 0
- source file is an image
    image_src_x           : 679
    image_src_y           : 1024
    image_src_pixels      : 695296
    image_src_type        : png
    image_src_bits        : 8
process file to /www/html/apache2/htdocs/cloud/picr/uploads/images/3/
- file size OK
- file mime OK : image/png
- new file name ext : jpg
- new file name body : 3_0c7b7a8d19ac20210b93c8e375927cbd
- file name safe format
- destination variables
    file_dst_path         : /www/html/apache2/htdocs/cloud/picr/uploads/images/3/
    file_dst_name_body    : 3-0c7b7a8d19ac20210b93c8e375927cbd
    file_dst_name_ext     : png
- checking for auto_rename
- destination file details
    file_dst_name         : 3-0c7b7a8d19ac20210b93c8e375927cbd.png
    file_dst_pathname     : /www/html/apache2/htdocs/cloud/picr/uploads/images/3/3-0c7b7a8d19ac20210b93c8e375927cbd.png
- 3-0c7b7a8d19ac20210b93c8e375927cbd.png doesn't exist already
- image resizing or conversion wanted
- source image is PNG
- resizing...
    ratio_fill_x         : -148 (-74;-74)
    image_src_x y        : 679 x 1024
    image_dst_x y        : 152 x 230
    resized image object created
- crop image : 0 -74 0 -74 
- converting...
    fills in transparency with default color
- saving image...
    JPEG image created
    image objects destroyed
- process OK
cleanup
- delete temp file /www/html/php/tmp/php41vtHF

**Comment by akwatra** [comment]
Hi Verot,
I have tested with browser proper via form upload and that file had extension png, 
so after image created, it keeps the png ext as a bug and did not rename to jpg.

issue came, when i was trying to open that image and that was not showing data in viewer,
then I dig into and found the bug. You please double check once at your end with png an extention image.

**Comment by verot** [comment]
I did try with PNG, and it converted to JPEG, with a .jpg extension:

system information
- class version           : 0.35dev
- operating system        : Linux
- PHP version             : 5.6.26-1
- GD version              : 2.2.3
- supported image types   : png jpg gif bmp
- open_basedir            : no restriction
- upload_max_filesize     : 8M (8388608 bytes)
- language                : en_GB
source is an uploaded file
- upload OK
- file name OK
determining MIME type
- Checking MIME type with Fileinfo PECL extension
    MAGIC path will not be used
    MIME type detected as image/png; charset=binary by Fileinfo PECL extension
- MIME validated as image/png
source variables
- You can use all these before calling process()
    file_src_name         : test.png
    file_src_name_body    : test
    file_src_name_ext     : png
    file_src_pathname     : /tmp/phptYEBz6
    file_src_mime         : image/png
    file_src_size         : 36021 (max= 8388608)
    file_src_error        : 0
- source file is an image
    image_src_x           : 150
    image_src_y           : 100
    image_src_pixels      : 15000
    image_src_type        : png
    image_src_bits        : 8
process file to tmp/
- file size OK
- file mime OK : image/png
- new file name ext : jpg
- file name safe format
- destination variables
    file_dst_path         : tmp/
    file_dst_name_body    : test
    file_dst_name_ext     : jpg
- checking for auto_rename
- destination file details
    file_dst_name         : test.jpg
    file_dst_pathname     : tmp/test.jpg
- test.jpg doesn't exist already
- image resizing or conversion wanted
- source image is PNG
- resizing...
    ratio_fill_y         : -30 (-15;-15)
    image_src_x y        : 150 x 100
    image_dst_x y        : 300 x 200
    resized image object created
- crop image : -15 0 -15 0 
- converting...
    fills in transparency with default color
- saving image...
    JPEG image created
    image objects destroyed
- process OK

**Comment by verot** [comment]
Try with the new master, it should work for you too.

**Comment by akwatra** [comment]
It's Working Now! 
Thx.

**Pull request closed without merging**
