### PR TITLE
Chrome image/x-ms-bmp problem

### PR DESCRIPTION
**Pull request by G4Zz0L1**
Chrome doesn't properly handle image/x-ms-bmp mime type
(see https://bugs.chromium.org/p/chromium/issues/detail?id=449489)

It's a quick fix, if you have something better do as you want.

### CODE REVIEW

**Comment by G4Zz0L1** [comment]
Sorry for the pr spam, it's my first and I've now learned how to do it.   :S

**Comment by verot** [comment]
Thank you for your patch.

I see the three lines added for the Chrome bug. But I also see some changes to the BMP code. What are these changes?

**Comment by G4Zz0L1** [comment]
I've found the original code for the BMP output (https://github.com/caizhifu/phpbmp/blob/master/bmp.php) without that the BMP with the x-ms-bmp won't work, at least with my test.

**Comment by verot** [comment]
Can you send me the BMP file you used for testing?

**Comment by G4Zz0L1** [comment]
I've taken a BMP online, via Google. The one I used was a 16 bit one, but I think any BMP will work for testing.

**Comment by verot** [comment]
I don't understand your three lines of code about Chrome. Why would you need to change the source file MIME type?

Besides, if the MIME is _x-ms-bmp_, the the class already recognizes the file as a BMP image.

**Comment by G4Zz0L1** [comment]
Check the link in the first post: chrome has problems with that mime type, and it treats it like a binary, prompting the download. That's the reason for the mime switch.

**Comment by verot** [comment]
I understand the Chrome bug. But I don't see how it applies to the upload class.

**Comment by G4Zz0L1** [comment]
I wa using the class for generate live thumbs, in the case of that BMP mime (without those fixes) it downloads the file, instead of visualize it.

**Comment by verot** [comment]
This is done outside of the class. See this code in the README:

```
$handle = new upload($_FILES['image_field']);
header('Content-type: image/bmp');
echo $handle->Process();
die();
```
It is where you set the content type. You don't have to change the class.

**Comment by G4Zz0L1** [comment]
I was using the src_mime to set the header, being generic. In your way I should switch for that BMP case, but it's doable. If you think it's not a class bug to be fixed, close this without problem.

**Comment by verot** [comment]
It should not be done within the class. Closing.

**Pull request closed without merging**
