### PR TITLE
PHP 7 compatibility

### PR DESCRIPTION
**Pull request by delafred**
PHP 7 full compatibility PHP 4 style constructor
http://php.net/manual/fr/migration70.deprecated.php

### CODE REVIEW

**Comment by verot** [comment]
Thank you for the patch. However, I want the class to remain compatible with PHP4 (and PHP5) for the moment. I have no time to check right now, but I think your patch breaks compatibility with PHP4.

**Comment by delafred** [comment]
Thx for your excellent job.
You're right this code will not work for php 4 and I undersand your choice.

Patch work for php 5 and 7

Cdly,

Frédéric Delamare


2015-12-08 15:08 GMT+01:00 Colin Verot <notifications@github.com>:

**Comment by mingtsay** [comment]
Related to #21. How about determine the version of PHP to provide the suitable code for it?

**Comment by verot** [comment]
If possible, I would like to keep it backward-compatible with PHP 4, 5 and 7. I don't think there is a way to have conditional code depending on the PHP version, for the constructor is the issue, but I amy be overlooking a solution.
But if it is not possible, I am happy to merge a patch with PHP 5 and 7 compatibility, and then we can add a note for PHP 4 users.

**Comment by verot** [comment]
Fixed in 5d95fb237

**Pull request closed without merging**
